-- Create the Active_Clients table
create table public."Active_Clients" (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  company_name text,
  location text,
  contact_number text,
  email text,
  requirement text,
  vacant_positions integer,
  status text default 'Active'
);

-- Create the Pending_Clients table
create table public."Pending_Clients" (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  company_name text,
  location text,
  contact_number text,
  email text,
  requirement text,
  vacant_positions integer,
  status text default 'Pending'
);

-- Add assigned_client column to candidates table
alter table public.candidates
add column assigned_client text;

-- Add comments column to candidates table
alter table public.candidates
add column comments text;


-- Add client_status column to candidates table
alter table public.candidates
add column client_status text;

-- Add feedback_report column to Pending_Clients table
alter table public."Pending_Clients"
add column feedback_report text;
