-- Create the New_Clients table
create table public."New_Clients" (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  company_name text,
  location text,
  contact_number text,
  email text,
  requirement text,
  vacant_positions integer,
  status text default 'Active'
);
